### ISSUE TITLE
Implement sentiment dataset

### ISSUE THREAD

**Issue by diogo-cruz** [EdoardoPona/predicting-inductive-biases-RL#11]
Implement dataset loading for the sentiment text generation case.
This consists of at least two things:

1. Finding the dataset online and loading it.
2. Modifying the dataset to control for target of spurious features (this may be done before or after loading the initial dataset, depending on what is most convenient).

**Comment by diogo-cruz** [comment]
1. Implementing the ToyPool-like class to load the already processed data (with the same structure as the Lovering data).
2. Preprocess the IMDb data:

- Clip the review (so only keep the first N tokens)
- Add target/spurious features

**Comment by diogo-cruz** [comment]
Probably done. To get the dataset, run
```
python imdb_dataset_preprocessing.py
```
from the `predicting-inductive-biases-RL` folder.

To use the dataset, use the label `sentiment_pool` (just as we were using `toy_pool` for toy+RL). Don't forget to pull the RL4LMs repo.

**Comment by diogo-cruz** [comment]
Note: to run successfully, this assumes that you already have the IMDb dataset. If not, run (in the instance) `cp /home/alex/nlp_data /home/[your name]`.

If your not in the instance, download the dataset in https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download, and store it in the `nlp_data` folder (in the same directory as `ASH_code`).

**Comment by AlexH-T** [comment]
I've implemented the truncation in imdb_dataset_preprocessing

**Comment by diogo-cruz** [comment]
Seems to be working, I'm closing.
