### ISSUE TITLE
Results collection for RL models

### ISSUE THREAD

**Issue by EdoardoPona** [EdoardoPona/predicting-inductive-biases-RL#6]
code that collects RL results and generates graphs will have to be rewritten for the RL models.

**Comment by EdoardoPona** [comment]
We need a script that runs RL experiments across different values of evidence rates.
eg. To start off you can look at the implementation of `train_rl4lm.py`

The main loop of this new script will be something like  
```
rates: List[int] = [...]
for r in rates:
    run_experiment(r, path, ...)
```
it is important that we save results for each rate in a path that is distinguishable. 

once that is implemented, we can loop over the results and graph the performances / rates out (see lovering paper) 

to do all of this, first we need to find a way to specify the `rate` parameter used by the `TextGenPool` from the custom rl4lm experiment config

**Comment by eliasschmied** [comment]
looping over rates is done, graphing is not

**Comment by diogo-cruz** [comment]
This is done since commit 28b577f644f1ad32415f0658ad24e3e60dd65a84
